apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fastapi/deployment.yaml
  - fastapi/service.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml
  - mysql/persistentVolumeClaim.yaml
  - mysql/secret.yaml
  - phpmyadmin/deployment.yaml
  - phpmyadmin/service.yaml
  - phpmyadmin/ingress.yaml
  - phpmyadmin/secret.yaml



patches:
  - patch.yaml

namespace: kustomize