apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - persistentvolumeclaim.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - phpmyadmin-deployment.yaml
  - phpmyadmin-service.yaml
  - hpa.yaml
  - ingress.yaml

namespace: kustomize
