# Default values for helm-exam.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "helm"

fastapi:
  name: "fastapi"
  replicaCount: 3
  image: mathiasbrl/exam_k8s_fastapi
          imagePullPolicy: Always
  service:
    port: 80
  hpa:
    maxReplicaCount: 6
    targetCPU: 70

pma:
  name: "phpmyadmin"
  replicaCount: 1
  service:
    type: NodePort
    port: 80
    nodePort: 30008

mysql:
  name: "mysql"
  replicaCount: 1
  database: "storedb"
  service:
    port: 3306
  pvc:
    accessMode: "ReadWriteOnce"
    storage: 10Gi
  secret:
    key: "password"
