apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: standard
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: mathiasbrl/exam_k8s_fastapi:latest
          ports:
            - containerPort: 8000