apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: standard
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql" 
              subPath: mysql
              name: mysql-pvc            
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root-password


      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc