apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  host: {{ .Values.mysql.name }}-service
  port: {{ .Values.mysql.service.port }}
  database: {{ .Values.mysql.database }}