apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ .Values.fastapi.name }}-hpa
 namespace: {{ .Values.namespace }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ .Values.fastapi.name }}
 minReplicas: {{ .Values.fastapi.replicaCount }}
 maxReplicas: {{ .Values.fastapi.hpa.maxReplicaCount }}
 targetCPUUtilizationPercentage: {{ .Values.fastapi.hpa.targetCPU }}