apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.mysql.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.pvc.storage }}
