apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{Values.mysql.name}}-statefulset
  namespace: {{.Values.namespace}}
  labels:
    app: {{Values.mysql.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{Values.mysql.name}}
  template:
    metadata:
      labels:
        app: {{Values.mysql.name}}
    spec:
      containers:
        - name: {{Values.mysql.name}}
          image: {{Values.mysql.name}}:latest
          ports:
            - containerPort: {{Values.mysql.service.port}}
          volumeMounts:
            - mountPath: "/var/lib/mysql" 
              subPath: {{Values.mysql.name}}
              name: {{Values.mysql.name}}-pvc            
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{Values.mysql.name}}-secrets
                  key: root-password


      volumes:
        - name: {{Values.mysql.name}}-pvc  
          persistentVolumeClaim:
            claimName: {{Values.mysql.name}}-pvc  